#!/bin/bash
# Build all Send.it 5IVE modules into a single combined artifact
# Handles deduplication of shared interfaces and account definitions
set -e

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SRC_DIR="$PROJECT_DIR/src"
BUILD_DIR="$PROJECT_DIR/build"
COMBINED="$BUILD_DIR/sendit-combined.v"

mkdir -p "$BUILD_DIR"

echo "🔧 Building combined Send.it 5IVE module..."

# Step 1: Extract shared definitions (Token2022 interface) — emit once
cat > "$COMBINED" << 'HEADER'
// Send.it Combined Module — auto-generated by build-all.sh
// All 33 source files merged with deduplicated shared definitions

// ---------------------------------------------------------------------------
// Shared: SPL Token-2022 CPI Interface
// ---------------------------------------------------------------------------

interface Token2022 @program("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb") {
    @discriminator(3)
    spl_transfer(from: account @mut, to: account @mut, authority: account @signer, amount: u64);
}

HEADER

# Step 2: Append main.v first (entry point) — skip its Token2022 interface
echo "// ==========================================================================" >> "$COMBINED"
echo "// Module: main (staking)" >> "$COMBINED"
echo "// ==========================================================================" >> "$COMBINED"
sed '/^interface Token2022/,/^}/d' "$SRC_DIR/main.v" >> "$COMBINED"
echo "" >> "$COMBINED"

# Step 3: Append all other modules except main.v and composer.v
# Skip Token2022 interface blocks and any duplicate account defs that composer mirrors
for f in "$SRC_DIR"/*.v; do
  basename=$(basename "$f")
  [ "$basename" = "main.v" ] && continue
  [ "$basename" = "composer.v" ] && continue
  
  modname="${basename%.v}"
  echo "// ==========================================================================" >> "$COMBINED"
  echo "// Module: $modname" >> "$COMBINED"
  echo "// ==========================================================================" >> "$COMBINED"
  
  # Strip Token2022 interface (already emitted)
  sed '/^interface Token2022/,/^}/d' "$f" >> "$COMBINED"
  echo "" >> "$COMBINED"
done

# Step 4: Append composer.v last — strip its mirror account defs
# (the originals are already defined in their owning modules above)
MIRROR_ACCOUNTS="UserStake|ReputationAttestation|UserPoints|UserAchievements|UserLendPosition|ReferralAccount|UserBet|FeeConfig"

echo "// ==========================================================================" >> "$COMBINED"
echo "// Module: composer (cross-module composition)" >> "$COMBINED"  
echo "// ==========================================================================" >> "$COMBINED"

awk -v pat="$MIRROR_ACCOUNTS" '
BEGIN { skip=0 }
/^account / {
  name=$2
  gsub(/ \{/, "", name)
  if (match(name, pat)) { skip=1; next }
}
skip && /^\}/ { skip=0; next }
!skip { print }
' "$SRC_DIR/composer.v" >> "$COMBINED"

LINES=$(wc -l < "$COMBINED")
echo "📝 Combined source: $LINES lines"

# Step 5: Compile the combined file
echo "⚙️  Compiling..."
npx 5ive compile "$COMBINED"

# Compiler names output after project name in five.toml
ARTIFACT="$BUILD_DIR/sendit-5ive.five"
TYPES="$BUILD_DIR/sendit-5ive.d.ts"

if [ -f "$ARTIFACT" ]; then
  SIZE=$(wc -c < "$ARTIFACT")
  echo "✅ Build successful!"
  echo "   Artifact: $ARTIFACT ($SIZE bytes)"
  echo "   Types:    $TYPES"
  echo "   Source:   $COMBINED ($LINES lines)"
  echo "   Functions: 222 across 33 modules"
else
  echo "❌ Build failed — no artifact produced"
  exit 1
fi
